# TODO ejercicio 02: completar este Dockerfile usando la imagen base de Orbis Data

# INSTRUCCIONES en exercises/02-docker/README.md

# Pistas:
# - La imagen correcta para Express es orbisdata/node-base:lts
# - Necesitás dos stages: uno para instalar deps, otro para la imagen final
# - El usuario debe ser node (no root)
# - El puerto es 3000
